//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lineas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lineas()
        {
            this.RutaLinea = new HashSet<RutaLinea>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Empresa { get; set; }
        public string Estado { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual Estado Estado1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutaLinea> RutaLinea { get; set; }
    }
}
